### PR TITLE
First cut at news

### PR DESCRIPTION
**Pull request by jadenisco**
Signed-off-by: John DeNisco <jadenisco@gmail.com>

### CODE REVIEW

**Comment by dbarach** [comment]
Let me know when you want me to merge this one…

**Comment by edwarnicke** [comment]
@nealtex01 could you have a look?

**Comment by nealtex01** [comment]
> @nealtex01 could you have a look?



> @nealtex01 could you have a look?

Well, I can see the code, but not a page preview.  Am I missing something?

**Comment by jadenisco** [comment]
> > @nealtex01 could you have a look?
> 
> Well, I can see the code, but not a page preview. Am I missing something?

Neal,

Thanks for taking a look. In general look at the last check below, then click on details. For thjs request: https://deploy-preview-8--fdio.netlify.com

All comments are welcome. The changes in this case were to the news page that was added. This was all a cut and paste from the main site. Each article is in the form of a .md file in content/news.

It would also be nice to get your comments on the front page. I am not crazy about the wording for fd.io or VPP.

**Comment by nealtex01** [comment]
Thx John, The news page looks great to me.

Circa home page, I think a little rework can help.  I'd be happy to take a crack if you like. I'm not (yet) proficient in Hugo and Netlify, so for this go round, would you mind if I mock it up and perhaps you code it? That will be the fastest path for now. Can that work?

Neal

**Comment by jadenisco** [comment]
> Thx John, The news page looks great to me.
> 
> Circa home page, I think a little rework can help. I'd be happy to take a crack if you like. I'm not (yet) proficient in Hugo and Netlify, so for this go round, would you mind if I mock it up and perhaps you code it? That will be the fastest path for now. Can that work?
> 
> Neal

Yes that would work.

**Comment by edwarnicke** [comment]
@jadenisco  @JDiGiglio had asked about the 'Announcements' section from the original page.  It looks like you've interleaved those in already, is that correct?

**Pull request merged**
