### PR TITLE
Update to frontpage in response to issue #13

### PR DESCRIPTION
**Pull request by edwarnicke**
Signed-off-by: Ed Warnicke <hagbard@gmail.com>

### CODE REVIEW

**Comment by edwarnicke** [comment]
Draft version of the response to issue #13

**Comment by dbarach** [comment]
lI'll be glad to merge this if you publish it...

**Comment by edwarnicke** [comment]
@dbarach Your attentiveness is much appreciated.  Wanted to get some input still from @nealtx01 who prosposed it in issue #13 (where he has a [mockup](https://github.com/FDio/site/files/3291719/fd.io.home.page.messaging.pdf) )

I have intentionally pushed this as a Draft so it doesn't get quite merged till conversation converges on it :)

**Comment by nealtex01** [comment]
And one more I just caught:

Change:

Deploy anywhere.
Deploy on bare metal, VM or container. x86, ARM, and PowerPC architectures. The future of packet processing. Now.

to:

Deploy anywhere.
Bare metal, VM or container. x86, ARM, and PowerPC architectures.

The future of packet processing. Now.

That last line should be separated from the Deploy Now point. It's meant as a closing caption. It should also be the same font size and color/bold as the words "Deploy Now".

**Comment by edwarnicke** [comment]
@nealtex01 How is this recent update: [preview](https://deploy-preview-15--fdio.netlify.com/) (note: same as previous preview link, also can be found inline at: 
Screen Shot 2019-06-17 at 6 19 29 PM

)

**Comment by nealtex01** [comment]
bueno!

**Comment by edwarnicke** [comment]
@nealtex01 Changes made.  I did add 'packet' to 'transport, session, and application' just to make sure it got covered :)

On the background color... that one is hysterical... I only added it because it was in your mockup :)

New version up on preview, how does it look?

**Comment by nealtex01** [comment]
Ed,

Looking good! Two nits...

1. Still need to do this one..."WHAT IS THE VECTOR PACKET PROCESSOR (VPP)?" should be "WHAT IS VECTOR PACKET PROCESSING (VPP)?"

2. Can you stretch the VPP text block so the word processing fits onto line two here as opposed to being orphaned...(i realize the site is responsive, but you have to go window REALLY wide to get there...)

"VPP’s host stack comprises packet, transport, session, and application layer protocols - enabling entire networking and security functions to be injected into software packet processing."

Neal

**Comment by nealtex01** [comment]
Just responded in GH. Yes the background color was just because i bastardized it in sketch just by creating an overlay :-) It looks great now!

**Comment by edwarnicke** [comment]
@nealtex01 Updated.  Let me know what you think :)

**Comment by nealtex01** [comment]
> @nealtex01 Updated. Let me know what you think :)

@edwarnicke The defense rests. Nothing further to add Your Honor!

**Comment by edwarnicke** [comment]
@JDiGiglio I've fixed your issues from #17 I think here in the PR.  Till its merged, its likely simpler for you to comment on the PR itself rather than opening separate issues :)

**Pull request merged**
